typography_spectrum: 0.5993257246445864
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7913491220679134
  lightness: 0.9540261209476739
  saturation: 0.29329927009530365
  rhythmicContrast: 0.26646797684952617
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75
analytics:
  google: UA-34786152-4
  facebook: null
  twitter: null
name: 4 Gems Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Kalamazoo Michigan High School Senior Photographer
description: Capturing your inner sparkle
purpose: []
