typography_spectrum: 0.5993257246445864
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7913491220679134
  lightness: 0.9540261209476739
  saturation: 0.29329927009530365
  rhythmicContrast: 0.26646797684952617
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75
analytics:
  google: UA-34786152-4
  facebook: null
  twitter: null
name: 4 Gems Photography
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About 4 Gems Photography
    id: 90bdd471-8fec-4f5f-9632-71721e5580f1
    type: content
  - name: About Eric Mazzone
    id: a4957c94-e683-486d-a494-b67bea68aea3
    type: content
favicon: null
title: Kalamazoo Michigan High School Senior Photographer
description: Capturing your inner sparkle!
purpose: []
