name: 4 Gems Photography
favicon: null
layout_spectrum: 0.22360354149714112
typography_spectrum: 0.5993257246445864
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7913491220679134
  lightness: 0.9540261209476739
  saturation: 0.29329927009530365
  rhythmicContrast: 0.26646797684952617
purpose: []
